### ISSUE TITLE
Block fly not work

### ISSUE THREAD

**Issue by l3unnyAnoF4** [OnyxianSoul/WorldGuardExtraFlags-1.17#1]
![image](https://user-images.githubusercontent.com/67956962/136431302-8747dd1d-60f8-4835-aa3f-746aed24a567.png)

**Comment by Happily-Coding** [comment]
I briefly looked into it, and the author seemed to be aware of this problem.
You can check this class, where there is a comment from the original author. My guess is at some point a change in the source code of one of the plugins broke the flag.
https://github.com/OnyxianSoul/WorldGuardExtraFlags-1.17/blob/2abb99593f09a147fd554e7720b21e68f92fc404/Spigot/src/main/java/net/goldtreeservers/worldguardextraflags/listeners/EssentialsListener.java

I didn't modify this flag in any way, so i don't really intend to fix the issue myself, however, if someone wants to make a pull request i'll gladly accept it.
Good luck
